---
name: X1201 Poweroff Guard
version: 0.5.6
slug: x1201_poweroff_guard
description: Test X1201 poweroff guard.
arch: 
  - aarch64
startup: initialize
init: false
boot: auto
hassio_role: manager
docker_api: true
apparmor: false
privileged: 
  - SYS_ADMIN
devices:
  - /dev/gpiochip0
