---
name: X1201 Poweroff Guard
version: 0.5.2
slug: x1201_poweroff_guard
description: Test X1201 poweroff guard.
arch: 
  - aarch64
startup: initialize
init: false
boot: auto
hassio_api: true
hassio_role: manager
host_dbus: true
docker_api: true
apparmor: false
privileged: 
  - SYS_ADMIN
  - SYS_RAWIO
devices:
  - /dev/gpiochip0
