name: "Yahboom RGB Cooling HAT"
description: "Yahboom RGB Cooling HAT"
version: "1.0.4"
slug: "yahboom_rgb_cooling_hat"
init: false
arch:
  - aarch64
log_level: info
startup: services
privileged:
  - SYS_ADMIN
devices:
  - /dev/i2c-1:/dev/i2c-1:rwm
device_tree: true
image: 
  psopso/yahboom_rgb_cooling_hat-{arch}