mqtt:
  sensor:
    - name: "X728 Battery Voltage"
      state_topic: "x728/battery_voltage"
      unit_of_measurement: "V"
      unique_id: "x728_battery_voltage"
      device:
        identifiers: ["x728_ups"]
        name: "X728 UPS"
        model: "X728"
        manufacturer: "Geekworm"

    - name: "X728 Battery Capacity"
      state_topic: "x728/battery_capacity"
      unit_of_measurement: "%"
      unique_id: "x728_battery_capacity"
      device:
        identifiers: ["x728_ups"]
        name: "X728 UPS"
        model: "X728"
        manufacturer: "Geekworm"
        
  binary_sensor:
    - name: "X728 Power Loss"
      state_topic: "x728/power_loss"
      payload_on: "1"
      payload_off: "0"
      unique_id: "x728_power_loss"
      device:
        identifiers: ["x728_ups"]
        name: "X728 UPS"
        model: "X728"
        manufacturer: "Geekworm"
