name: "Yahboom RGB Cooling HAT"
description: " It manages fan speed) based on CPU temperature, provides RGB LED status control, and displays system information on the integrated OLED display."
version: "1.0.5"
slug: "yahboom_rgb_cooling_hat"
url: "https://github.com/YahboomTechnology/Raspberry-Pi-RGB-Cooling-HAT"
init: false
arch:
  - aarch64
log_level: info
startup: services
privileged:
  - SYS_ADMIN
devices:
  - /dev/i2c-1:/dev/i2c-1:rwm
device_tree: true
#image: 
#  psopso/yahboom_rgb_cooling_hat-{arch}