---
name: InfluxDB2
version: 1.0.3
slug: influxdb2
description: Scalable datastore for metrics, events, and real-time analytics
url: https://github.com/hassio-addons/addon-influxdb
ingress: false
ingress_port: 1337
ingress_stream: false
panel_icon: mdi:chart-areaspline
startup: services
homeassistant: 0.92.0b2
hassio_api: true
arch:
  - aarch64
  - amd64
  - armv7
  - i386
init: false
map:
  - share:rw
  - ssl
ports:
  80/tcp: null
  8086/tcp: 8086
  8088/tcp: 8088
ports_description:
  80/tcp: Web interface (Not required for Ingress)
  8086/tcp: InfluxDB server
  8088/tcp: RPC service for backup and restore
auth_api: true
options:
  auth: true
  reporting: true
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  envvars: []
  admintoken: ""
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  auth: bool
  reporting: bool
  ssl: bool
  certfile: str
  keyfile: str
  envvars:
    - name: match(^INFLUXDB_([A-Z0-9_])+$)
      value: str
  admintoken: str?
  leave_front_door_open: bool?
image: 
  psopso/influxdb2
